export const dashboardConstants = {
    GETALL_REQUEST: 'DASHBOARD_GETALL_REQUEST',
    GETALL_SUCCESS: 'DASHBOARD_GETALL_SUCCESS',
    GETALL_FAILURE: 'DASHBOARD_GETALL_FAILURE',

    SAVE_REQUEST: 'DASHBOARD_SAVE_REQUEST',
    SAVE_SUCCESS: 'DASHBOARD_SAVE_SUCCESS',
    SAVE_FAILURE: 'DASHBOARD_SAVE_FAILURE',

    GETDICTIONARIES_REQUEST: 'DASHBOARD_GETDICTIONARIES_REQUEST',
    GETDICTIONARIES_SUCCESS: 'DASHBOARD_GETDICTIONARIES_SUCCESS',
    GETDICTIONARIES_FAILURE: 'DASHBOARD_GETDICTIONARIES_FAILURE',
}